const unsplash = (id, w = 1800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const CATEGORIES = [
  { id: "all", label: "All plates" },
  { id: "landscape", label: "Landscape" },
  { id: "architecture", label: "Architecture" },
  { id: "urban", label: "Urban" },
  { id: "nature", label: "Nature" },
  { id: "abstract", label: "Abstract" },
  { id: "yours", label: "Yours" },
];

export const PHOTOS = [
  {
    id: "solstice",
    title: "Solstice Ridge",
    photographer: "Luca Bravo",
    location: "Dolomites, Italy",
    year: 2016,
    category: "landscape",
    featured: true,
    unsplash: "photo-1501785888041-af3ef285b470",
    caption: "Morning light catching a high alpine lake after a night of still air.",
  },
  {
    id: "atrium",
    title: "Glass Atrium",
    photographer: "Joel Filipe",
    location: "Valencia, Spain",
    year: 2017,
    category: "architecture",
    unsplash: "photo-1486325212027-8081e485255e",
    caption: "A ribbed vault of steel and glass, photographed as a single plate.",
  },
  {
    id: "harbor",
    title: "Harbor Hour",
    photographer: "Sean Oulashin",
    location: "Honolulu, Hawaiʻi",
    year: 2016,
    category: "landscape",
    unsplash: "photo-1507525428034-b723cf961d3e",
    caption: "Late afternoon on a long beach, tide drawing a pale line inland.",
  },
  {
    id: "neon",
    title: "After Rain",
    photographer: "Andre Benz",
    location: "Tokyo, Japan",
    year: 2017,
    category: "urban",
    unsplash: "photo-1540959733332-eab4deabeeaf",
    caption: "Wet asphalt and signage after a brief summer storm.",
  },
  {
    id: "canopy",
    title: "Old Canopy",
    photographer: "John Towner",
    location: "Redwood forest",
    year: 2016,
    category: "nature",
    unsplash: "photo-1441974231531-c6227db76b6e",
    caption: "Looking up through a stand of coastal redwoods.",
  },
  {
    id: "aurora",
    title: "Green Hour",
    photographer: "Jonatan Pie",
    location: "Iceland",
    year: 2017,
    category: "landscape",
    unsplash: "photo-1531366936337-7cf89ea49503",
    caption: "Aurora over a frozen shoreline, long exposure.",
  },
  {
    id: "library",
    title: "Stacks",
    photographer: "Iñaki del Olmo",
    location: "Trinity College, Dublin",
    year: 2016,
    category: "architecture",
    unsplash: "photo-1521587760476-6c12a4b040da",
    caption: "The long room, barrels of oak and a high clerestory.",
  },
  {
    id: "dune",
    title: "Windward",
    photographer: "Ken Cheung",
    location: "Namib Desert",
    year: 2018,
    category: "landscape",
    unsplash: "photo-1509316785289-025f5b846b35",
    caption: "A single ridgeline holding the last of the sun.",
  },
  {
    id: "bridge",
    title: "Night Span",
    photographer: "Pedro Lastra",
    location: "New York, USA",
    year: 2016,
    category: "urban",
    unsplash: "photo-1480714378408-67cf0d13bc1b",
    caption: "The city from the water, towers stacked like type.",
  },
  {
    id: "bloom",
    title: "Field Notes",
    photographer: "Serge Kutuzov",
    location: "Netherlands",
    year: 2018,
    category: "nature",
    unsplash: "photo-1490750967868-88aa4486c946",
    caption: "A close plate of color, almost abstract at full bleed.",
  },
  {
    id: "fogline",
    title: "Fog Line",
    photographer: "Kalen Emsley",
    location: "Banff, Canada",
    year: 2016,
    category: "landscape",
    unsplash: "photo-1506905925346-21bda4d32df4",
    caption: "A valley holding weather like a bowl.",
  },
  {
    id: "marble",
    title: "Vein",
    photographer: "Paweł Czerwiński",
    location: "Studio",
    year: 2018,
    category: "abstract",
    unsplash: "photo-1557672172-298e090bd0f1",
    caption: "Ink in water, photographed as a still catalog plate.",
  },
  {
    id: "arcade",
    title: "Arcade",
    photographer: "Francesca Tosolini",
    location: "Lisbon, Portugal",
    year: 2017,
    category: "architecture",
    unsplash: "photo-1511818966892-d7d671e672a2",
    caption: "Repeating arches, one vanishing point.",
  },
  {
    id: "tide",
    title: "Long Fetch",
    photographer: "Joseph Barrientos",
    location: "Pacific coast",
    year: 2015,
    category: "landscape",
    unsplash: "photo-1439066615861-d1af74d74000",
    caption: "A still alpine lake, peaks inverted in the water.",
  },
  {
    id: "lantern",
    title: "Lantern Street",
    photographer: "Héctor J. Rivas",
    location: "Kyoto, Japan",
    year: 2017,
    category: "urban",
    unsplash: "photo-1493976040374-85c8e12f0c0e",
    caption: "A narrow street after dusk, paper lanterns still lit.",
  },
  {
    id: "cinder",
    title: "Cinder Field",
    photographer: "Benjamin Voros",
    location: "High desert",
    year: 2017,
    category: "landscape",
    unsplash: "photo-1469474968028-56623f02e42e",
    caption: "Sun breaking over a volcanic ridge.",
  },
  {
    id: "studio",
    title: "Quiet Room",
    photographer: "Minh Pham",
    location: "Interior study",
    year: 2018,
    category: "architecture",
    unsplash: "photo-1505691938895-1758d7feb511",
    caption: "A domestic interior treated as a catalog object.",
  },
  {
    id: "ice",
    title: "Blue Ice",
    photographer: "Benjamin Voros",
    location: "Jökulsárlón, Iceland",
    year: 2016,
    category: "nature",
    unsplash: "photo-1454496522488-7a8e488e8606",
    caption: "A berg grounded in black sand.",
  },
  {
    id: "grid",
    title: "Facade Grid",
    photographer: "Lance Anderson",
    location: "Chicago, USA",
    year: 2016,
    category: "architecture",
    unsplash: "photo-1486406146926-c627a92ad1ab",
    caption: "A curtain wall reduced to rhythm and reflection.",
  },
  {
    id: "meadow",
    title: "Late Meadow",
    photographer: "Tim Swaan",
    location: "Swiss Alps",
    year: 2017,
    category: "nature",
    unsplash: "photo-1470071459604-3b5ec3a7fe05",
    caption: "Fog lifting off a high meadow at first light.",
  },
  {
    id: "signal",
    title: "Signal",
    photographer: "Federico Bottos",
    location: "Studio",
    year: 2018,
    category: "abstract",
    unsplash: "photo-1574169208507-84376144848b",
    caption: "Color fields arranged like a printer’s proof.",
  },
  {
    id: "plaza",
    title: "Night Plaza",
    photographer: "Luca Bravo",
    location: "Venice, Italy",
    year: 2016,
    category: "urban",
    unsplash: "photo-1523906834658-6e24ef2386f9",
    caption: "A canal corridor, stone and water sharing the same tone.",
  },
  {
    id: "cedar",
    title: "Cedar Path",
    photographer: "Jay Mantri",
    location: "Pacific Northwest",
    year: 2015,
    category: "nature",
    unsplash: "photo-1447752875215-b2761acb3c5d",
    caption: "A trail under a closed canopy, moss holding the light.",
  },
  {
    id: "horizon",
    title: "Salt Horizon",
    photographer: "Jared Erondu",
    location: "Salar de Uyuni",
    year: 2015,
    category: "landscape",
    unsplash: "photo-1418065460487-3e41a6c84dc5",
    caption: "A weather front moving over an empty salt flat.",
  },
].map((photo, index) => ({
  ...photo,
  index,
  src: unsplash(photo.unsplash, 2200),
  thumb: unsplash(photo.unsplash, 720),
  hero: unsplash(photo.unsplash, 2400),
  local: false,
}));

export function plateNumber(index) {
  return String(index + 1).padStart(2, "0");
}

export function fallbackSrc(id) {
  return `https://picsum.photos/seed/${encodeURIComponent(id)}/1600/1100`;
}
