from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]


class AndroidProjectTests(unittest.TestCase):
    def test_android_module_exists(self):
        self.assertTrue((ROOT / "android" / "app" / "src" / "main" / "AndroidManifest.xml").is_file())
        self.assertTrue((ROOT / "android" / "app" / "src" / "main" / "java" / "com" / "aperture" / "catalog" / "MainActivity.kt").is_file())
        self.assertTrue((ROOT / "android" / "app" / "src" / "main" / "java" / "com" / "aperture" / "catalog" / "CatalogStore.kt").is_file())
        self.assertTrue((ROOT / "android" / "gradlew").is_file())

    def test_web_bridge_hooks(self):
        app_js = (ROOT / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("ApertureAndroid", app_js)
        self.assertIn("aperture-native-catalog", app_js)
        self.assertIn("apertureHandleBack", app_js)
        self.assertIn("openRecent", app_js)
        self.assertIn("recent-plate", app_js)
        self.assertIn("header-plate", app_js)
        self.assertIn("recent-tabs", app_js)
        self.assertIn("openRecents", app_js)
        self.assertIn("selectedIds", app_js)
        self.assertIn("is-selected", app_js)
        self.assertIn("downloadCurrent", app_js)
        self.assertIn("ensureDownloadsAccess", app_js)
        self.assertIn("startIn: \"downloads\"", app_js)
        self.assertIn("ApertureAndroid?.requestDownloads", app_js)
        self.assertIn("ApertureAndroid?.hasDownloadsAccess", app_js)
        self.assertIn("openDownloadsFolder", app_js)
        self.assertIn("apertureDownloadProgress", app_js)
        self.assertIn("openPostForm", app_js)
        self.assertIn("openCrop", app_js)
        self.assertIn("applyCrop", app_js)
        self.assertIn("sendCanvasPost", app_js)
        self.assertIn("openCanvasBoard", app_js)
        self.assertIn("saveCanvasPost", app_js)
        self.assertIn("encodeCanvasPostOnEth", app_js)
        self.assertIn("encodeCanvasBoardOnEth", app_js)
        self.assertIn("/api/posts/nft", app_js)
        self.assertIn("ApertureAndroid?.attachPostNft", app_js)
        self.assertNotIn("sendNft", app_js)
        self.assertIn("encodePhotoOnEth", app_js)
        self.assertIn("attachLongPress", app_js)
        self.assertIn("ApertureAndroid.share", app_js)
        self.assertIn("ApertureAndroid?.savePost", app_js)
        self.assertIn("aperturePostProgress", app_js)
        self.assertIn("/api/post", app_js)
        self.assertIn("/api/posts", app_js)
        self.assertIn("/media/posts/", app_js)
        self.assertNotIn("openChainLedger", app_js)
        self.assertNotIn("/api/chain", app_js)
        self.assertNotIn("/api/vault", app_js)
        self.assertNotIn("/api/sync", app_js)
        self.assertNotIn("sendFolder", app_js)
        self.assertNotIn("js/chain.js", app_js)
        self.assertIn("openSkinEditor", app_js)
        self.assertIn("theme.bootSkin", app_js)
        self.assertIn("encodeCatalogOnEth", app_js)
        self.assertIn("encodePhotoOnEth", app_js)
        self.assertIn("nftPlaceholderSrc", app_js)
        self.assertIn("Posting on Canvasboard", app_js)
        self.assertIn("Canvasboard", app_js)
        self.assertNotIn("/api/search", app_js)
        self.assertNotIn("searchCatalogOnServer", app_js)
        self.assertNotIn("initializeShardSearch", app_js)
        self.assertIn("/api/eth", app_js)
        self.assertIn("ApertureAndroid?.ethEncode", app_js)
        self.assertIn("ApertureAndroid?.ethOpen", app_js)
        self.assertIn("openEthShard", app_js)
        self.assertIn("/api/eth/open", app_js)
        self.assertIn("/api/eth/shard", app_js)
        self.assertNotIn("encodeCatalogOnXrp", app_js)
        self.assertNotIn("/api/xrp", app_js)
        eth_js = (ROOT / "js" / "eth.js").read_text(encoding="utf-8")
        self.assertIn("aperture-eth-shard-v1", eth_js)
        self.assertIn("checksumAddress", eth_js)
        self.assertIn("encodePlate", eth_js)
        self.assertIn("nftMetadata", eth_js)
        self.assertIn("tokenIdFromHash", eth_js)
        self.assertIn("erc721", eth_js)
        self.assertIn("/api/eth/nft/", eth_js)
        self.assertIn("parsePointer", eth_js)
        self.assertIn("eths:", eth_js)
        self.assertTrue(not (ROOT / "js" / "xrp.js").exists())
        theme_js = (ROOT / "js" / "theme.js").read_text(encoding="utf-8")
        self.assertIn("PRESETS", theme_js)
        self.assertIn("Aero sky", theme_js)
        self.assertIn("applySkin", theme_js)
        self.assertIn("ApertureAndroid?.saveSkin", theme_js)
        self.assertIn("/api/skin", theme_js)
        interface_js = (ROOT / "js" / "interface.js").read_text(encoding="utf-8")
        self.assertIn("SERVERS", interface_js)
        self.assertIn("ENGINES", interface_js)
        self.assertIn("matchRecord", interface_js)
        self.assertIn("/api/interface", interface_js)
        self.assertIn("ApertureAndroid?.saveInterface", interface_js)
        self.assertIn("ApertureAndroid?.loadInterface", interface_js)
        self.assertNotIn("/api/search", interface_js)
        self.assertIn("openPlugMenu", app_js)
        self.assertIn("./interface.js", app_js)
        self.assertIn("./bobble.js", app_js)
        self.assertIn("attachBobbles", app_js)
        self.assertNotIn("searchHits", app_js)
        bobble_js = (ROOT / "js" / "bobble.js").read_text(encoding="utf-8")
        self.assertIn("detectModels", bobble_js)
        self.assertIn("FaceDetector", bobble_js)
        self.assertIn("detectByFeatures", bobble_js)
        self.assertIn("enqueue(() => detectByFeatures(img))", bobble_js)
        self.assertIn("faceScore", bobble_js)
        self.assertIn('scale(1.48)', bobble_js)
        self.assertIn("integralImage", bobble_js)
        self.assertIn("attachBobbles", bobble_js)
        self.assertIn("DEFAULT_FACE", bobble_js)
        self.assertIn("assumedFace", bobble_js)
        self.assertIn("bobble-face", bobble_js)
        self.assertIn("bobble-rim", bobble_js)
        self.assertIn("waitForBox", bobble_js)
        self.assertIn("toggleBobble", bobble_js)
        self.assertIn("restoreBobble", bobble_js)
        self.assertIn("BOBBLE_KEY", bobble_js)
        self.assertIn("ApertureAndroid?.saveBobble", bobble_js)
        self.assertIn("ApertureAndroid?.loadBobble", bobble_js)
        self.assertIn("viewerFrame", app_js)
        self.assertIn("toggleBobbleEffect", app_js)
        self.assertIn("bobbleBtn", app_js)

    def test_recent_plates_in_opener(self):
        html = (ROOT / "index.html").read_text(encoding="utf-8")
        css = (ROOT / "css" / "styles.css").read_text(encoding="utf-8")
        data = (ROOT / "js" / "data.js").read_text(encoding="utf-8")
        self.assertIn('id="recentRow"', html)
        self.assertIn('id="recentTabs"', html)
        self.assertIn('id="downloadBar"', html)
        self.assertIn('id="downloadsPermit"', html)
        self.assertIn('id="openerDownloadsBtn"', html)
        self.assertIn("Use Downloads", html)
        self.assertIn('id="cropForm"', html)
        self.assertIn('id="postForm"', html)
        self.assertIn('id="postShare"', html)
        self.assertIn('id="canvasBoard"', html)
        self.assertIn('id="canvasNftAll"', html)
        self.assertIn("Post on Canvasboard", html)
        self.assertIn(">Share</button>", html)
        self.assertNotIn("Send as a post", html)
        self.assertNotIn("New post", html)
        self.assertNotIn('id="chainLedger"', html)
        self.assertNotIn("Send folder", html)
        self.assertNotIn("Receive folder", html)
        self.assertNotIn('id="sendBar"', html)
        self.assertNotIn('id="syncInput"', html)
        self.assertNotIn(".apsync", html)
        self.assertIn("Theme editor", html)
        self.assertIn('id="skinEditor"', html)
        self.assertIn('id="themeBtn"', html)
        self.assertIn('id="plugMenu"', html)
        self.assertIn('id="plugBtn"', html)
        self.assertIn("Plug servers", html)
        self.assertIn('id="sd-bobble"', html)
        self.assertIn("feFuncA", html)
        self.assertIn("feGaussianBlur", html)
        self.assertIn('scale="38"', html)
        self.assertIn('id="bobbleBtn"', html)
        self.assertIn("Bobble on / off", html)
        self.assertIn("<kbd>P</kbd> bobble", html)
        self.assertIn('id="heroBobble"', html)
        self.assertIn('id="viewerBobble"', html)
        self.assertIn('id="viewerFrame"', html)
        self.assertIn('id="ethShard"', html)
        self.assertIn("Attach as NFT", html)
        self.assertIn('id="canvasBar"', html)
        self.assertNotIn('id="ethBar"', html)
        self.assertIn('id="ethBtn"', html)
        self.assertIn('id="ethPointerInput"', html)
        self.assertIn("Open NFT", html)
        self.assertIn("eths:", html)
        self.assertNotIn('id="xrpLedger"', html)
        self.assertNotIn("Encode onto XRP", html)
        self.assertIn("eth-shard", css)
        self.assertIn("eth-pointer-field", css)
        self.assertIn("eth-bar", css)
        self.assertIn("canvas-bar", css)
        self.assertIn("canvas-board", css)
        self.assertIn("canvas-wall", css)
        self.assertIn("canvas-nft-btn", css)
        self.assertNotIn("xrp-ledger", css)
        self.assertIn("skin-editor", css)
        self.assertIn("plug-menu", css)
        self.assertIn("plug-bay", css)
        self.assertIn("plug-search", css)
        self.assertIn("bobble-layer", css)
        self.assertIn("bobble-model", css)
        self.assertIn("bobble-rim", css)
        self.assertIn("sd-bobble", css)
        self.assertIn("bobble-off", css)
        self.assertIn("drop-shadow", css)
        self.assertIn("radial-gradient(ellipse 52% 50% at 50% 46%", css)
        self.assertIn("scale(1.48)", css)
        self.assertIn("card-photo", css)
        self.assertIn("--sky", css)
        self.assertIn("Search titles, places", html)
        self.assertIn("Long-press", html)
        self.assertIn("Crop, then post on Canvasboard", html)
        self.assertIn("Share", html)
        self.assertNotIn("chain-ledger", css)
        self.assertNotIn("send-bar", css)
        self.assertIn("column-count: 2", css)
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr))", css)
        self.assertIn("recent-tabs", css)
        self.assertIn("download-bar", css)
        self.assertIn("downloads-permit", css)
        self.assertIn("crop-form", css)
        self.assertIn("crop-box", css)
        self.assertIn("post-form", css)
        self.assertIn("is-selected", css)
        self.assertIn("is-together", css)
        self.assertIn("recent-slideshow", css)
        self.assertIn("flex: 1 1 0", css)
        self.assertIn("grid-template-columns: 1fr", css)
        self.assertIn("header-plate", css)
        self.assertIn("MAX_RECENTS = 3", data)
        self.assertIn("MAX_RECENT_SLIDES = 8", data)
        app_js = (ROOT / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("toggleRecentSelection", app_js)
        self.assertIn("aria-multiselectable", app_js)
        self.assertIn("slidesFromCatalog", app_js)
        self.assertIn("readySlides", app_js)
        self.assertIn("startRecentSlideshow", app_js)
        self.assertIn("recentSlidePlates", app_js)
        self.assertIn("recent-slideshow", app_js)

    def test_installable_apk_is_present(self):
        apk = ROOT / "releases" / "Aperture.apk"
        self.assertTrue(apk.is_file())
        self.assertGreater(apk.stat().st_size, 100_000)
        self.assertEqual(apk.read_bytes()[:4], b"PK\x03\x04")

    def test_native_cache_keys(self):
        store = (ROOT / "android" / "app" / "src" / "main" / "java" / "com" / "aperture" / "catalog" / "CatalogStore.kt").read_text(encoding="utf-8")
        main = (ROOT / "android" / "app" / "src" / "main" / "java" / "com" / "aperture" / "catalog" / "MainActivity.kt").read_text(encoding="utf-8")
        self.assertIn('KEY_URI = "lastFolder"', store)
        self.assertIn("takePersistableUriPermission", store)
        self.assertIn("KEY_RECENTS", store)
        self.assertIn("MAX_RECENTS = 3", store)
        self.assertIn("/api/catalog", main)
        self.assertIn("/api/recent-cover", main)
        self.assertIn("fun openRecent", main)
        self.assertIn("fun openRecents", main)
        self.assertIn("fun openRecents", store)
        self.assertIn("fun download", store)
        self.assertIn("fun recentCoverResponse", store)
        self.assertIn("nthImage", store)
        self.assertIn("MAX_RECENT_SLIDES", store)
        self.assertIn('getQueryParameter("p")', main)
        self.assertIn("fun download", main)
        self.assertIn("fun requestDownloads", main)
        self.assertIn("fun hasDownloadsAccess", main)
        self.assertIn("fun openDownloads", main)
        self.assertIn("fun hasDownloadsAccess", store)
        self.assertIn("fun openDownloads", store)
        self.assertIn("DIRECTORY_DOWNLOADS", store)
        self.assertIn("READ_MEDIA_IMAGES", store)
        self.assertIn("fun exportToFile", store)
        self.assertIn("fun share", main)
        self.assertIn("FileProvider", main)
        self.assertNotIn("fun chainAppend", main)
        self.assertNotIn("fun chainAppend", store)
        self.assertNotIn("fun chainLock", store)
        self.assertNotIn("KEY_CHAIN", store)
        self.assertNotIn("/api/chain", main)
        self.assertNotIn("/api/vault", main)
        self.assertNotIn("/api/sync", main)
        self.assertNotIn("fun shareSync", main)
        self.assertNotIn(".apsync", store)
        self.assertIn("ACTION_SEND", main)
        self.assertIn("fun loadSkin", main)
        self.assertIn("fun saveSkin", main)
        self.assertIn("fun setChrome", main)
        self.assertIn("fun skinResponse", store)
        self.assertIn("KEY_SKIN", store)
        self.assertIn("/api/skin", main)
        self.assertIn("KEY_INTERFACE", store)
        self.assertIn("fun loadInterface", store)
        self.assertIn("fun saveInterface", store)
        self.assertIn("fun interfaceResponse", store)
        self.assertIn("fun loadInterface", main)
        self.assertIn("fun saveInterface", main)
        self.assertIn("KEY_BOBBLE", store)
        self.assertIn("fun loadBobble", store)
        self.assertIn("fun saveBobble", store)
        self.assertIn("fun loadBobble", main)
        self.assertIn("fun saveBobble", main)
        self.assertIn("/api/interface", main)
        self.assertIn("/api/eth", main)
        self.assertIn("/api/eth/nft/", main)
        self.assertIn("/api/posts", main)
        self.assertIn("/media/posts/", main)
        self.assertNotIn("/api/search", main)
        self.assertNotIn("fun searchCatalog", main)
        self.assertNotIn("fun searchCatalog", store)
        self.assertIn("fun nftResponse", store)
        self.assertIn("fun attachNft", store)
        self.assertIn("erc721", store)
        self.assertIn("fun ethEncode", main)
        self.assertIn("fun ethOpen", main)
        self.assertIn("fun ethEncode", store)
        self.assertIn("fun ethOpen", store)
        self.assertIn("fun ethEncodeFolder", store)
        self.assertIn("fun decodeDataUrl", store)
        self.assertIn("data:", store)
        self.assertIn("fun savePost", main)
        self.assertIn("fun savePost", store)
        self.assertIn("fun postsListing", store)
        self.assertIn("fun attachPostNft", store)
        self.assertIn("fun attachPostNft", main)
        self.assertIn("KEY_POSTS", store)
        self.assertIn("/api/eth/shard", main)
        self.assertIn("/media/eth/", main)
        self.assertIn("KEY_ETH", store)
        self.assertIn("aperture-eth-shard", store)
        self.assertIn("eths:", store)
        self.assertNotIn("/api/xrp", main)
        self.assertNotIn("aperture-xrp-cipher-v1", store)
        self.assertNotIn("apxs1:", store)
        manifest = (ROOT / "android" / "app" / "src" / "main" / "AndroidManifest.xml").read_text(encoding="utf-8")
        self.assertIn("WRITE_EXTERNAL_STORAGE", manifest)
        self.assertIn("READ_EXTERNAL_STORAGE", manifest)
        self.assertIn("READ_MEDIA_IMAGES", manifest)
        self.assertIn("androidx.core.content.FileProvider", manifest)
        self.assertNotIn("application/x-aperture-sync", manifest)
        self.assertTrue((ROOT / "android" / "app" / "src" / "main" / "res" / "xml" / "file_paths.xml").is_file())


if __name__ == "__main__":
    unittest.main()
